// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nixiang.dbo;

namespace nixiang.Migrations
{
    [DbContext(typeof(TargetContext))]
    [Migration("20190523165212_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("nixiang.dbo.BusinessLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("BusinessLeads");
                });

            modelBuilder.Entity("nixiang.dbo.Financial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BusinessLeadId");

                    b.HasKey("Id");

                    b.HasIndex("BusinessLeadId");

                    b.ToTable("Financials");
                });

            modelBuilder.Entity("nixiang.dbo.TargetContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<int?>("BusinessLeadId");

                    b.Property<string>("Email");

                    b.Property<string>("FamilyName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("PersonalName");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessLeadId");

                    b.ToTable("TargetContacts");
                });

            modelBuilder.Entity("nixiang.dbo.Financial", b =>
                {
                    b.HasOne("nixiang.dbo.BusinessLead")
                        .WithMany("FinancialData")
                        .HasForeignKey("BusinessLeadId");
                });

            modelBuilder.Entity("nixiang.dbo.TargetContact", b =>
                {
                    b.HasOne("nixiang.dbo.BusinessLead")
                        .WithMany("PrimaryContacts")
                        .HasForeignKey("BusinessLeadId");
                });
#pragma warning restore 612, 618
        }
    }
}
