// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buzyleeds.dbo;

namespace buzyleeds.Migrations
{
    [DbContext(typeof(TargetContext))]
    partial class TargetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("buzyleeds.dbo.BusinessLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("BusinessLeads");
                });

            modelBuilder.Entity("buzyleeds.dbo.Financial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LeadId");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Financials");
                });

            modelBuilder.Entity("buzyleeds.dbo.TargetContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("Email");

                    b.Property<string>("FamilyName");

                    b.Property<int>("LeadId");

                    b.Property<string>("MiddleName");

                    b.Property<string>("PersonalName");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("TargetContacts");
                });

            modelBuilder.Entity("buzyleeds.dbo.Financial", b =>
                {
                    b.HasOne("buzyleeds.dbo.BusinessLead", "BusinessLead")
                        .WithMany("FinancialData")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("buzyleeds.dbo.TargetContact", b =>
                {
                    b.HasOne("buzyleeds.dbo.BusinessLead", "BusinessLead")
                        .WithMany("PrimaryContacts")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
